INSERT INTO USERS (ID, FULL_NAME, EMAIL, PASSWORD, CONFIRMED) VALUES (-1, 'admin', 'admin', STRINGDECODE('x61Ey612Kl2gpFL56FT9weDnpSo4AV8j8+qx2AuTHdRyY036xxzTTrw10Wq3+4qQyB+XURPWx1ON\nxp3Y3pB37A=='), true);
INSERT INTO USERS (ID, FULL_NAME, EMAIL, PASSWORD, CONFIRMED) VALUES (-2, 'user', 'user', STRINGDECODE('x61Ey612Kl2gpFL56FT9weDnpSo4AV8j8+qx2AuTHdRyY036xxzTTrw10Wq3+4qQyB+XURPWx1ON\nxp3Y3pB37A=='), true);
INSERT INTO USERS (ID, FULL_NAME, EMAIL, PASSWORD, CONFIRMED) VALUES (-3, 'manager', 'manager', STRINGDECODE('x61Ey612Kl2gpFL56FT9weDnpSo4AV8j8+qx2AuTHdRyY036xxzTTrw10Wq3+4qQyB+XURPWx1ON\nxp3Y3pB37A=='), true);

INSERT INTO ROLES (ID, NAME, DESCRIPTION) VALUES (-1, 'admin', 'admin');
INSERT INTO ROLES (ID, NAME, DESCRIPTION) VALUES (-2, 'user', 'user');
INSERT INTO ROLES (ID, NAME, DESCRIPTION) VALUES (-3, 'manager', 'manager');

INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (-1, -1);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (-1, -2);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (-1, -3);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (-2, -2);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (-3, -3);

INSERT INTO PUBLIC.VEHICLE (ID, CLIMAT, DESCRIPTION, DOORS, GEARBOX, MODEL, PASSENGERS, TANK, YEAR, RATE) VALUES (-1, true, 'Volkswagen Jetta', 4, 'MAN', 'Sedan', 5, 55, 2016,5.0);
INSERT INTO PUBLIC.VEHICLE (ID, CLIMAT, DESCRIPTION, DOORS, GEARBOX, MODEL, PASSENGERS, TANK, YEAR, RATE) VALUES (-2, true, 'Skoda Fabia', 4, 'AUT', 'Hatchback', 5, 45, 2014,5.0);
INSERT INTO PUBLIC.VEHICLE (ID, CLIMAT, DESCRIPTION, DOORS, GEARBOX, MODEL, PASSENGERS, TANK, YEAR, RATE) VALUES (-3, true, 'Volkswagen Golf DSG', 3, 'AUT', 'Hatchback', 5, 45, 2017,7.2);
INSERT INTO PUBLIC.VEHICLE (ID, CLIMAT, DESCRIPTION, DOORS, GEARBOX, MODEL, PASSENGERS, TANK, YEAR, RATE) VALUES (-4, true, 'Volkswagen Passat Variant', 4, 'MAN', 'Universal', 5, 65, 2017,8.5);
INSERT INTO PUBLIC.VEHICLE (ID, CLIMAT, DESCRIPTION, DOORS, GEARBOX, MODEL, PASSENGERS, TANK, YEAR, RATE) VALUES (-5, true, 'Mercedes-Benz E220d', 4, 'AUT', 'Universal', 5, 65, 2016,10.0);
INSERT INTO PUBLIC.VEHICLE (ID, CLIMAT, DESCRIPTION, DOORS, GEARBOX, MODEL, PASSENGERS, TANK, YEAR, RATE) VALUES (-6, true, 'Toyota C-HR HSD', 5, 'AUT', 'Hatchback', 5, 45, 2017,12);
INSERT INTO PUBLIC.VEHICLE (ID, CLIMAT, DESCRIPTION, DOORS, GEARBOX, MODEL, PASSENGERS, TANK, YEAR, RATE) VALUES (-7, true, 'BMW 320i', 3, 'AUT', 'Sedan', 4, 65, 2015,10.0);
INSERT INTO PUBLIC.VEHICLE (ID, CLIMAT, DESCRIPTION, DOORS, GEARBOX, MODEL, PASSENGERS, TANK, YEAR, RATE) VALUES (-8, true, 'Toyota Land Cruiser', 5, 'AUT', 'SUV', 7, 65, 2017,20.0);
INSERT INTO PUBLIC.VEHICLE (ID, CLIMAT, DESCRIPTION, DOORS, GEARBOX, MODEL, PASSENGERS, TANK, YEAR, RATE) VALUES (-9, true, 'Toyota Rav4 AT', 4, 'AUT', 'SUV', 5, 45, 2017,10.0);
INSERT INTO PUBLIC.VEHICLE (ID, CLIMAT, DESCRIPTION, DOORS, GEARBOX, MODEL, PASSENGERS, TANK, YEAR, RATE) VALUES (-10, true, 'Nissan X-Trail ', 4, 'AUT', 'SUV', 5, 55, 2014,12.5);



